import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import Search from '../components/Search'
import { useState } from 'react'
import Filter from '../components/Filter'
import axios from 'axios'
import CountryCard from '../components/CountryCard'
import CountryList from '../components/CountryList'


export async function getStaticProps(){
  const data = await axios.get('https://restcountries.com/v3.1/all')

  return {
    props: {
        countries: data.data
    }
}

}


export default function Home({countries}) {
  console.log(countries)

  return (
    <div className='bg-gray-100 font-nunito'>
      <Head>
        <title>Rest Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout/>
      <div className='w-11/12 m-auto mt-40 flex flex-row justify-between items-center'>
        <Search />
        <Filter />
        </div>
        <CountryList countries={countries}/>
    </div>
  )
}
