import Head from 'next/head'
import Layout from '../components/Layout'
import Search from '../components/Search'
import { useState } from 'react'
import Filter from '../components/Filter'
import axios from 'axios'
import CountryList from '../components/CountryList'


export async function getStaticProps(){
  const data = await axios.get('https://restcountries.com/v3.1/all')

  return {
    props: {
        countries: data.data
    }
}

}


export default function Home({countries}) {

  const [dropdown, showDropdown] = useState(false);
  const [query, setQuery] = useState('');
  const filteredCountries = countries.filter(country => country.name.common.toLowerCase().includes(query));

  const handleChange = (e) => {
    setQuery(e.target.value)
  }
  
  const handleDropdown = () => {
    showDropdown(!dropdown)
  }

  console.log(filteredCountries)

  return (
    <div className='bg-gray-100 font-nunito'>
      <Head>
        <title>Rest Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout/>
      <div className='w-11/12 m-auto mt-40 flex flex-row justify-between items-center'>
        <Search handleChange={handleChange}/>
        <Filter handleDropdown={handleDropdown} dropdown={dropdown}/>
        </div>
        <CountryList countries={filteredCountries}/>
    </div>
  )
}
